[book]
authors = ["Colin Walters"]
language = "en"
multilingual = false
src = "src"
title = "bootc"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.header-footer]
headers = []
footers = [
  { padding = "\n---\n<p style=\"font-size:11px\">The Linux FoundationÂ® (TLF) has registered trademarks and uses trademarks. For a list of TLF trademarks, see <a href=\"https://www.linuxfoundation.org/trademark-usage/\">Trademark Usage.</a></p>" }
]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
optional = true
